/*
 * Demoiselle Framework
 *
 * License: GNU Lesser General Public License (LGPL), version 3 or later.
 * See the lgpl.txt file in the root directory or <https://www.gnu.org/licenses/lgpl.html>.
 */
package org.demoiselle.jee.core.annotation;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.PARAMETER;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import jakarta.inject.Qualifier;

/**
 * Marks an interface as a message bundle. Interfaces annotated with this
 * annotation will have dynamic proxy implementations generated by the
 * {@link org.demoiselle.jee.core.message.MessageBundleExtension} CDI extension.
 * Methods on the interface should be annotated with {@link MessageTemplate}
 * to define the message key used for lookup in ResourceBundle properties files.
 *
 * @author SERPRO
 */
@Qualifier
@Retention(RUNTIME)
@Target({TYPE, METHOD, FIELD, PARAMETER})
public @interface MessageBundle {
}
