/*
 * Demoiselle Framework
 *
 * License: GNU Lesser General Public License (LGPL), version 3 or later.
 * See the lgpl.txt file in the root directory or <https://www.gnu.org/licenses/lgpl.html>.
 */
package org.demoiselle.jee.security.interceptor;

import net.jqwik.api.*;
import net.jqwik.api.constraints.IntRange;
import net.jqwik.api.lifecycle.BeforeProperty;

import jakarta.enterprise.inject.Instance;
import jakarta.enterprise.util.TypeLiteral;
import jakarta.ws.rs.core.*;
import jakarta.ws.rs.ext.RuntimeDelegate;

import org.demoiselle.jee.rest.DemoiselleRestConfig;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.util.*;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

// Feature: rfc-standards-compliance, Property 14: Resposta 429 contém Retry-After consistente com SlidingWindowCounter
/**
 * Property-based test for {@link RateLimitInterceptor#buildRateLimitResponse(int)}.
 *
 * <p>Verifies that for any retryAfter value, the generated 429 response has the
 * correct HTTP status and a Retry-After header matching the input value.</p>
 *
 * <p><b>Validates: Requirements 6.1, 6.2, 9.1, 9.4</b></p>
 */
class RateLimitRetryAfterPropertyTest {

    @BeforeProperty
    void installRuntimeDelegate() {
        RuntimeDelegate.setInstance(new HeaderCapturingRuntimeDelegate());
    }

    // Feature: rfc-standards-compliance, Property 14: Resposta 429 contém Retry-After consistente com SlidingWindowCounter
    /**
     * Property 14: For any response 429 generated by {@code RateLimitInterceptor},
     * the Retry-After header value must equal the retryAfter parameter, and the
     * HTTP status must be 429.
     *
     * <p><b>Validates: Requirements 6.1, 6.2, 9.1, 9.4</b></p>
     */
    @Property(tries = 100)
    void retryAfterHeaderMatchesParameterAndStatusIs429(
            @ForAll @IntRange(min = 1, max = 60) int retryAfter
    ) throws Exception {
        RateLimitInterceptor interceptor = createInterceptor();

        Response response = interceptor.buildRateLimitResponse(retryAfter);

        // Status must be 429
        assertEquals(429, response.getStatus(),
                "Response status must be 429 for retryAfter=" + retryAfter);

        // Retry-After header must match the retryAfter parameter
        String retryAfterHeader = response.getHeaderString("Retry-After");
        assertNotNull(retryAfterHeader,
                "Retry-After header must be present for retryAfter=" + retryAfter);
        assertEquals(String.valueOf(retryAfter), retryAfterHeader,
                "Retry-After header value must equal the retryAfter parameter. " +
                "Expected: " + retryAfter + ", Got: " + retryAfterHeader);
    }

    // ---- Helper ----

    /**
     * Creates a RateLimitInterceptor with a stub Instance&lt;DemoiselleRestConfig&gt;
     * injected via reflection. The config is not resolvable (simulates missing REST module),
     * which triggers the legacy JSON format path.
     */
    private RateLimitInterceptor createInterceptor() throws Exception {
        RateLimitInterceptor interceptor = new RateLimitInterceptor();

        Field restConfigField = RateLimitInterceptor.class.getDeclaredField("restConfig");
        restConfigField.setAccessible(true);
        restConfigField.set(interceptor, new UnresolvableInstance());

        return interceptor;
    }

    // ---- Stub Instance<DemoiselleRestConfig> that is not resolvable ----

    @SuppressWarnings("serial")
    static class UnresolvableInstance implements Instance<DemoiselleRestConfig> {
        @Override public DemoiselleRestConfig get() { throw new IllegalStateException("Not resolvable"); }
        @Override public boolean isResolvable() { return false; }
        @Override public boolean isUnsatisfied() { return true; }
        @Override public boolean isAmbiguous() { return false; }
        @Override public Instance<DemoiselleRestConfig> select(Annotation... qualifiers) { return this; }
        @Override public <U extends DemoiselleRestConfig> Instance<U> select(Class<U> subtype, Annotation... qualifiers) { throw new UnsupportedOperationException(); }
        @Override public <U extends DemoiselleRestConfig> Instance<U> select(TypeLiteral<U> subtype, Annotation... qualifiers) { throw new UnsupportedOperationException(); }
        @Override public void destroy(DemoiselleRestConfig instance) {}
        @Override public Handle<DemoiselleRestConfig> getHandle() { throw new UnsupportedOperationException(); }
        @Override public Iterable<Handle<DemoiselleRestConfig>> handles() { throw new UnsupportedOperationException(); }
        @Override public Iterator<DemoiselleRestConfig> iterator() { return Collections.emptyIterator(); }
        @Override public Stream<DemoiselleRestConfig> stream() { return Stream.empty(); }
    }

    // ── Minimal RuntimeDelegate that captures headers ──────────────

    /**
     * A minimal JAX-RS RuntimeDelegate for unit testing that captures headers
     * set via {@code Response.ResponseBuilder.header()}, so we can verify
     * the Retry-After header value.
     */
    static class HeaderCapturingRuntimeDelegate extends RuntimeDelegate {

        @Override
        public Response.ResponseBuilder createResponseBuilder() {
            return new HeaderCapturingResponseBuilder();
        }

        @Override
        public UriBuilder createUriBuilder() { throw new UnsupportedOperationException(); }

        @Override
        public Variant.VariantListBuilder createVariantListBuilder() { throw new UnsupportedOperationException(); }

        @Override
        public <T> T createEndpoint(Application application, Class<T> endpointType) { throw new UnsupportedOperationException(); }

        @Override
        @SuppressWarnings("unchecked")
        public <T> HeaderDelegate<T> createHeaderDelegate(Class<T> type) {
            if (type == MediaType.class) {
                return (HeaderDelegate<T>) new MediaTypeHeaderDelegate();
            }
            throw new UnsupportedOperationException("No header delegate for " + type);
        }

        @Override
        public Link.Builder createLinkBuilder() { throw new UnsupportedOperationException(); }

        @Override
        public EntityPart.Builder createEntityPartBuilder(String partName) { throw new UnsupportedOperationException(); }

        @Override
        public java.util.concurrent.CompletionStage<jakarta.ws.rs.SeBootstrap.Instance> bootstrap(
                Class<? extends Application> clazz, jakarta.ws.rs.SeBootstrap.Configuration configuration) {
            throw new UnsupportedOperationException();
        }

        @Override
        public java.util.concurrent.CompletionStage<jakarta.ws.rs.SeBootstrap.Instance> bootstrap(
                Application application, jakarta.ws.rs.SeBootstrap.Configuration configuration) {
            throw new UnsupportedOperationException();
        }

        @Override
        public jakarta.ws.rs.SeBootstrap.Configuration.Builder createConfigurationBuilder() {
            throw new UnsupportedOperationException();
        }
    }

    // ── MediaType header delegate ──────────────────────────────────

    static class MediaTypeHeaderDelegate implements RuntimeDelegate.HeaderDelegate<MediaType> {
        @Override
        public MediaType fromString(String value) {
            if (value == null) return null;
            String[] parts = value.split("/", 2);
            if (parts.length == 2) {
                return new MediaType(parts[0].trim(), parts[1].trim());
            }
            return new MediaType(value, null);
        }

        @Override
        public String toString(MediaType value) {
            if (value == null) return null;
            return value.getType() + "/" + value.getSubtype();
        }
    }

    // ── Response Builder that captures headers ─────────────────────

    static class HeaderCapturingResponseBuilder extends Response.ResponseBuilder {
        private int status;
        private Object entity;
        private MediaType mediaType;
        private final MultivaluedMap<String, Object> headers = new MultivaluedHashMap<>();

        @Override
        public Response build() {
            return new HeaderCapturingResponse(status, entity, mediaType, headers);
        }

        @Override
        public Response.ResponseBuilder clone() {
            HeaderCapturingResponseBuilder clone = new HeaderCapturingResponseBuilder();
            clone.status = this.status;
            clone.entity = this.entity;
            clone.mediaType = this.mediaType;
            clone.headers.putAll(this.headers);
            return clone;
        }

        @Override public Response.ResponseBuilder status(int status) { this.status = status; return this; }
        @Override public Response.ResponseBuilder status(int status, String reasonPhrase) { this.status = status; return this; }

        @Override
        public Response.ResponseBuilder entity(Object entity) { this.entity = entity; return this; }

        @Override
        public Response.ResponseBuilder entity(Object entity, java.lang.annotation.Annotation[] annotations) { this.entity = entity; return this; }

        @Override
        public Response.ResponseBuilder header(String name, Object value) {
            if (value != null) {
                headers.add(name, value);
            }
            return this;
        }

        @Override
        public Response.ResponseBuilder type(MediaType type) { this.mediaType = type; return this; }

        @Override
        public Response.ResponseBuilder type(String type) {
            if (type != null) {
                this.mediaType = MediaType.valueOf(type);
            }
            return this;
        }

        // ── No-op stubs for unused builder methods ──
        @Override public Response.ResponseBuilder allow(String... methods) { return this; }
        @Override public Response.ResponseBuilder allow(Set<String> methods) { return this; }
        @Override public Response.ResponseBuilder cacheControl(CacheControl cacheControl) { return this; }
        @Override public Response.ResponseBuilder encoding(String encoding) { return this; }
        @Override public Response.ResponseBuilder replaceAll(MultivaluedMap<String, Object> headers) { return this; }
        @Override public Response.ResponseBuilder language(String language) { return this; }
        @Override public Response.ResponseBuilder language(Locale language) { return this; }
        @Override public Response.ResponseBuilder variant(Variant variant) { return this; }
        @Override public Response.ResponseBuilder contentLocation(java.net.URI location) { return this; }
        @Override public Response.ResponseBuilder cookie(NewCookie... cookies) { return this; }
        @Override public Response.ResponseBuilder expires(Date expires) { return this; }
        @Override public Response.ResponseBuilder lastModified(Date lastModified) { return this; }
        @Override public Response.ResponseBuilder location(java.net.URI location) { return this; }
        @Override public Response.ResponseBuilder tag(EntityTag tag) { return this; }
        @Override public Response.ResponseBuilder tag(String tag) { return this; }
        @Override public Response.ResponseBuilder variants(Variant... variants) { return this; }
        @Override public Response.ResponseBuilder variants(List<Variant> variants) { return this; }
        @Override public Response.ResponseBuilder links(Link... links) { return this; }
        @Override public Response.ResponseBuilder link(java.net.URI uri, String rel) { return this; }
        @Override public Response.ResponseBuilder link(String uri, String rel) { return this; }
    }

    // ── Response that exposes captured headers ─────────────────────

    static class HeaderCapturingResponse extends Response {
        private final int status;
        private final Object entity;
        private final MediaType mediaType;
        private final MultivaluedMap<String, Object> headers;

        HeaderCapturingResponse(int status, Object entity, MediaType mediaType,
                                MultivaluedMap<String, Object> headers) {
            this.status = status;
            this.entity = entity;
            this.mediaType = mediaType;
            this.headers = new MultivaluedHashMap<>(headers);
        }

        @Override public int getStatus() { return status; }

        @Override
        public StatusType getStatusInfo() {
            return Response.Status.fromStatusCode(status);
        }

        @Override public Object getEntity() { return entity; }
        @Override public boolean hasEntity() { return entity != null; }
        @Override public MediaType getMediaType() { return mediaType; }

        @Override
        public MultivaluedMap<String, Object> getHeaders() { return headers; }

        @Override
        public MultivaluedMap<String, Object> getMetadata() { return headers; }

        @Override
        public MultivaluedMap<String, String> getStringHeaders() {
            MultivaluedMap<String, String> stringHeaders = new MultivaluedHashMap<>();
            for (Map.Entry<String, List<Object>> entry : headers.entrySet()) {
                for (Object val : entry.getValue()) {
                    stringHeaders.add(entry.getKey(), val != null ? val.toString() : null);
                }
            }
            return stringHeaders;
        }

        @Override
        public String getHeaderString(String name) {
            List<Object> values = headers.get(name);
            if (values == null || values.isEmpty()) return null;
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < values.size(); i++) {
                if (i > 0) sb.append(",");
                sb.append(values.get(i));
            }
            return sb.toString();
        }

        // ── Minimal stubs for unused Response methods ──
        @Override public <T> T readEntity(Class<T> entityType) { throw new UnsupportedOperationException(); }
        @Override public <T> T readEntity(GenericType<T> entityType) { throw new UnsupportedOperationException(); }
        @Override public <T> T readEntity(Class<T> entityType, java.lang.annotation.Annotation[] annotations) { throw new UnsupportedOperationException(); }
        @Override public <T> T readEntity(GenericType<T> entityType, java.lang.annotation.Annotation[] annotations) { throw new UnsupportedOperationException(); }
        @Override public boolean bufferEntity() { return false; }
        @Override public void close() {}
        @Override public Locale getLanguage() { return null; }
        @Override public int getLength() { return -1; }
        @Override public Set<String> getAllowedMethods() { return Set.of(); }
        @Override public Map<String, NewCookie> getCookies() { return Map.of(); }
        @Override public EntityTag getEntityTag() { return null; }
        @Override public Date getDate() { return null; }
        @Override public Date getLastModified() { return null; }
        @Override public java.net.URI getLocation() { return null; }
        @Override public Set<Link> getLinks() { return Set.of(); }
        @Override public boolean hasLink(String relation) { return false; }
        @Override public Link getLink(String relation) { return null; }
        @Override public Link.Builder getLinkBuilder(String relation) { return null; }
    }
}
