/*
 * Demoiselle Framework
 *
 * License: GNU Lesser General Public License (LGPL), version 3 or later.
 * See the lgpl.txt file in the root directory or <https://www.gnu.org/licenses/lgpl.html>.
 */
package org.demoiselle.jee.security.jwt.impl;

import java.util.List;
import java.util.Map;

import jakarta.annotation.Priority;
import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;
import static jakarta.ws.rs.Priorities.AUTHORIZATION;
import jakarta.ws.rs.core.Response;

import org.demoiselle.jee.security.jwt.api.ClaimsEnricher;

import org.demoiselle.jee.core.api.security.DemoiselleUser;
import org.demoiselle.jee.core.api.security.Token;
import org.demoiselle.jee.core.api.security.TokenManager;
import org.demoiselle.jee.core.api.security.TokenType;
import org.demoiselle.jee.security.exception.DemoiselleSecurityException;
import org.demoiselle.jee.security.message.DemoiselleSecurityJWTMessages;
import org.jose4j.jws.JsonWebSignature;
import org.jose4j.jwt.JwtClaims;
import org.jose4j.jwt.MalformedClaimException;
import org.jose4j.jwt.consumer.InvalidJwtException;
import org.jose4j.jwt.consumer.JwtConsumer;
import org.jose4j.jwt.consumer.JwtConsumerBuilder;
import org.jose4j.lang.JoseException;

/**
 * The security risk component JWT use a strategy where a pair of asymmetric
 * keys is necessary. The keys can be generated by you on linux
 * https://help.ubuntu.com/community/SSH/OpenSSH/Keys or leave the parameters
 * blank and see the log suggested keys The JWT standard is one of the safest
 * and performers today, to learn more check https://jwt.io/
 *
 * @author SERPRO
 */
@RequestScoped
@Priority(AUTHORIZATION)
public class TokenManagerImpl implements TokenManager {

    @Inject
    private KeyPairHolder keyPairHolder;

    @Inject
    private KeyRotationManager keyRotationManager;

    @Inject
    private Token token;

    @Inject
    private DemoiselleSecurityJWTConfig config;

    @Inject
    private DemoiselleUser loggedUser;

    @Inject
    private DemoiselleSecurityJWTMessages bundle;

    @Inject
    private TokenBlacklist tokenBlacklist;

    @Inject
    private Instance<ClaimsEnricher> claimsEnrichers;

    @Inject
    private Instance<RefreshTokenManager> refreshTokenManagerInstance;

    private String lastRefreshToken;

    /**
     * Pick up the token that is in the request scope and draws the user into
     * the token validating the user at this time
     *
     * @return DemoiselleUser principal
     */
    @Override
    public DemoiselleUser getUser() {
        return getUser(null, null);
    }

    /**
     * Pick up the token that is in the request scope and draws the user into
     * the token validating the user at this time
     *
     * @return DemoiselleUser principal
     */
    @Override
    @SuppressWarnings({"unchecked", "rawtypes"})
    public DemoiselleUser getUser(String issuer, String audience) {
        if (token.getKey() != null && !token.getKey().isEmpty() && token.getType().equals(TokenType.JWT)) {
            try {
                // Extract algorithm from JWT header and verify against allowedAlgorithms
                List<String> allowedAlgs = config.getAllowedAlgorithmsList();
                if (!allowedAlgs.isEmpty()) {
                    try {
                        JsonWebSignature headerJws = new JsonWebSignature();
                        headerJws.setCompactSerialization(token.getKey());
                        String tokenAlg = headerJws.getAlgorithmHeaderValue();
                        if (tokenAlg == null || !allowedAlgs.contains(tokenAlg)) {
                            throw new DemoiselleSecurityException(bundle.algorithmNotAllowed(), Response.Status.UNAUTHORIZED.getStatusCode());
                        }
                    } catch (JoseException e) {
                        throw new DemoiselleSecurityException(bundle.algorithmNotAllowed(), Response.Status.UNAUTHORIZED.getStatusCode());
                    }
                }

                // Extract kid from JWT header for key rotation support
                String kid = null;
                try {
                    JsonWebSignature kidJws = new JsonWebSignature();
                    kidJws.setCompactSerialization(token.getKey());
                    kid = kidJws.getKeyIdHeaderValue();
                } catch (JoseException e) {
                    // If we can't extract kid, proceed with fallback
                }

                JwtConsumer jwtConsumer = new JwtConsumerBuilder()
                        .setRequireExpirationTime()
                        .setAllowedClockSkewInSeconds(config.getClockSkewSeconds())
                        .setExpectedIssuer(issuer != null ? issuer : config.getIssuer())
                        .setExpectedAudience(audience != null ? audience : config.getAudience())
                        .setEvaluationTime(org.jose4j.jwt.NumericDate.now())
                        .setVerificationKey(keyRotationManager.getPublicKey(kid))
                        .build();
                JwtClaims jwtClaims = jwtConsumer.processToClaims(token.getKey());

                // Check if the token's JTI is blacklisted (revoked)
                try {
                    String jti = jwtClaims.getJwtId();
                    if (jti != null && tokenBlacklist.isBlacklisted(jti)) {
                        throw new DemoiselleSecurityException(bundle.tokenBlacklisted(), Response.Status.UNAUTHORIZED.getStatusCode());
                    }
                } catch (MalformedClaimException e) {
                    // JTI claim is malformed; proceed without blacklist check
                }

                loggedUser.setIdentity((String) jwtClaims.getClaimValue("identity"));
                loggedUser.setName((String) jwtClaims.getClaimValue("name"));
                List<String> list = (List<String>) jwtClaims.getClaimValue("roles");
                list.stream().forEach((string) -> {
                    loggedUser.addRole(string);
                });

                Map<String, List<String>> mappermissions = (Map) jwtClaims.getClaimValue("permissions");
                mappermissions.entrySet().stream().forEach((entry) -> {
                    String key = entry.getKey();
                    List<String> value = entry.getValue();
                    value.stream().forEach((string) -> {
                        loggedUser.addPermission(key, string);
                    });
                });

                Map<String, String> mapparams = (Map) jwtClaims.getClaimValue("params");
                mapparams.entrySet().stream().forEach((entry) -> {
                    loggedUser.addParam(entry.getKey(), entry.getValue());
                });

                // Invoke all registered ClaimsEnricher implementations
                if (claimsEnrichers != null) {
                    for (ClaimsEnricher enricher : claimsEnrichers) {
                        enricher.extract(jwtClaims, loggedUser);
                    }
                }

                return loggedUser;
            } catch (InvalidJwtException ex) {
                loggedUser = null;
                token.setKey(null);
                throw new DemoiselleSecurityException(bundle.expired(), Response.Status.UNAUTHORIZED.getStatusCode(), ex);
            }
        }
        return null;
    }

    @Override
    public void setUser(DemoiselleUser user) {
        setUser(user, null, null);
    }

    @Override
    public void setUser(DemoiselleUser user, String issuer, String audience) {
        long time = (org.jose4j.jwt.NumericDate.now().getValueInMillis() + (config.getTimetoLiveMilliseconds()));
        try {
            JwtClaims claims = new JwtClaims();
            claims.setIssuer(issuer != null ? issuer : config.getIssuer());
            claims.setExpirationTime(org.jose4j.jwt.NumericDate.fromMilliseconds(time));
            claims.setAudience(audience != null ? audience : config.getAudience());
            claims.setGeneratedJwtId();
            claims.setIssuedAtToNow();
            claims.setNotBeforeMinutesInThePast(1);

            claims.setClaim("identity", (user.getIdentity()));
            claims.setClaim("name", (user.getName()));
            claims.setClaim("roles", (user.getRoles()));
            claims.setClaim("permissions", (user.getPermissions()));
            claims.setClaim("params", (user.getParams()));

            // Invoke all registered ClaimsEnricher implementations
            if (claimsEnrichers != null) {
                for (ClaimsEnricher enricher : claimsEnrichers) {
                    enricher.enrich(claims, user);
                }
            }

            JsonWebSignature jws = new JsonWebSignature();
            jws.setPayload(claims.toJson());
            jws.setKey(keyRotationManager.getActivePrivateKey());
            jws.setKeyIdHeaderValue(keyRotationManager.getActiveKeyId());
            // Use first algorithm from allowedAlgorithms, falling back to algorithmIdentifiers
            List<String> allowedAlgs = config.getAllowedAlgorithmsList();
            String signingAlgorithm = (!allowedAlgs.isEmpty()) ? allowedAlgs.get(0) : config.getAlgorithmIdentifiers();
            jws.setAlgorithmHeaderValue(signingAlgorithm);
            token.setKey(jws.getCompactSerialization());
            token.setType(TokenType.JWT);

            // Generate refresh token if RefreshTokenManager is available
            try {
                if (refreshTokenManagerInstance != null && !refreshTokenManagerInstance.isUnsatisfied()) {
                    lastRefreshToken = refreshTokenManagerInstance.get().generateRefreshToken(user.getIdentity());
                }
            } catch (Exception e) {
                // Graceful degradation: if refresh token generation fails, setUser still works
                lastRefreshToken = null;
            }
        } catch (JoseException ex) {
            throw new DemoiselleSecurityException(bundle.general(), Response.Status.UNAUTHORIZED.getStatusCode(), ex);
        }

    }

    /**
     * Returns the last generated refresh token, or null if not available.
     *
     * @return the refresh token string, or null
     */
    public String getLastRefreshToken() {
        return lastRefreshToken;
    }

    @Override
    public boolean validate() {
        return getUser() != null;
    }

    @Override
    public boolean validate(String issuer, String audience) {
        return getUser(issuer, audience) != null;
    }

    /**
     * Clears the JWT token from the request scope.
     * <p>
     * Note: JWT tokens are stateless — this method only removes the token
     * reference from the current request-scoped {@link Token} bean. It does
     * NOT invalidate the token on the server side. For true revocation,
     * a server-side token blacklist (e.g., database or cache) is required.
     * </p>
     *
     * @param user the user to remove (not used directly; the request-scoped token is cleared)
     */
    @Override
    public void removeUser(DemoiselleUser user) {
        // Extract JTI and exp from the current token and blacklist it
        if (token.getKey() != null && !token.getKey().isEmpty() && token.getType() != null && token.getType().equals(TokenType.JWT)) {
            try {
                // Parse the token without validation to extract claims for blacklisting
                JwtConsumer jwtConsumer = new JwtConsumerBuilder()
                        .setSkipAllValidators()
                        .setDisableRequireSignature()
                        .setSkipSignatureVerification()
                        .build();
                JwtClaims jwtClaims = jwtConsumer.processToClaims(token.getKey());
                String jti = jwtClaims.getJwtId();
                if (jti != null && !jti.isEmpty()) {
                    long exp = jwtClaims.getExpirationTime().getValueInMillis();
                    tokenBlacklist.blacklist(jti, exp);
                }
            } catch (InvalidJwtException | MalformedClaimException e) {
                // If we can't parse the token, just clear it without blacklisting
            }
        }
        token.setKey(null);
    }

}
